- defaults:
    link:
      relink: true

- clean: ['-']


- link:
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
    ~/.vimrc: vimrc


- shell:
  - [git submodule update --init --recursive, Installing submodules]
